using System.ComponentModel.DataAnnotations;
using System.Net;
using UrlShortener.Models;
using UrlShortener.Repository;

namespace UrlShortener.Services;

public interface IUrlServices
{
    Task<ServiceResult<Urls>> CreateShortUrlAsync (Guid userId, string longrl, DateTime? expiredAt);
}

public class UrlServices: IUrlServices
{
    private readonly IUrlRepository _urlRepo;
    private readonly ILogger<UrlServices> _logger;
    private Random _random;

    public UrlServices(IUrlRepository urlRepository, ILogger<UrlServices> logger)
    {
        this._urlRepo = urlRepository;
        this._logger = logger;
        this._random = new Random();
    }

    public async Task<ServiceResult<Urls>> CreateShortUrlAsync (Guid userId, string longUrl, DateTime? expiredAt)
    {
        try
        {
            // Generate the short code
            // Short code to be generated by making use of the Base62-Encoding.
            // Base62-Encode allows to generate a random large byte that will be converted to base 62
            // The base62 is technically [0-9][a-z][A-Z]
            const int lengthOfUrl = 8;
            var base62Encoding = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
            string generatedCode = "";
            int i = 0;
            while (i < lengthOfUrl)
            {
                var randomChar = this._random.Next(base62Encoding.Length);
                char randombase62Char = base62Encoding[randomChar];
                generatedCode += randombase62Char;
                i += 1;
            }

            // Save to database
            Urls createdUrl = await this._urlRepo.CreateUrlsAsync(new Urls
            {
                Code = generatedCode,
                UserId = userId,
                OriginalUrl = longUrl,
                ExpiresAt = expiredAt,
                CreatedAt = DateTime.UtcNow,
                IsActive = true
            });
            return new ServiceResult<Urls>
            {
                Success = true,
                Data = createdUrl
            };
        } 
        catch (Exception e)
        {
            this._logger.LogError(e, "Create url service: failed to create new url");
            return new ServiceResult<Urls>
            {
                Success = false,
                Error = "internal server error",
                ErrorCode = (int)HttpStatusCode.InternalServerError
            };
        }
    }
}